service: aws-lambda

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:933649612231:table/measurers-dev

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
  saveTask:
    handler: src/createTask.createTask
    events:
      - http:
          path: /tasks
          method: post
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - http:
          path: /tasks
          method: get
  getTask:
    handler: src/getTask.getTask
    events:
      - http:
          path: /tasks/{id}
          method: get
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - http:
          path: /tasks/{id}
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH